version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file: .env
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py initadmin &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    extra_hosts:
      host.docker.internal: host-gateway
  
  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - ./db:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    restart: always
